index.html
students/sara_martins/sara_martins.html

- Criei uma pasta com nome sara_martins dentro da pasta 'students'
- Copie o arquivo 'cv_template.html' e renomeie com o nome sara_martins
- Na section class="students", substitui com meu nome o 'id="student-name"' e o texto da div class="name" com meu nome e sobrenome
- Completei o link para a página do meu currículo

Adicionando CV da Sara

---

index.html
students/natalya-peixoto/natalya_peixoto.html

-Editei meu nome e id no index html
- criei pasta com meu nome, copiei o arquivo cv_template e editei com o meu nome.

primeiro edit de nome dos arquivos

---

index.html
students/gabriela_daltoe_fortuna/cv_gabriela_daltoe_fortuna.html

Adição do nome Gabriela ao index e adição da pasta Gabriela com o CV Gabriela.

Add nome Gabriela ao index e add pasta com cv Gabriela

---

index.html
students/example/priscila_santtos/priscila_santtos.html

Index atualizado e currículo na pasta students.

inclusão do nome no index.html e da pasta estudante na pasta students

---

index.html
students/gisele_santin/gisele_santin.html

Editei meu nome no index.html e criei uma pasta com meu nome e arquivo html.

Currículo Gisele Santin

---

index.html
students/juliana_mokrejs/juliana_mokrejs.html

-Inclusão do meu nome e link para minha página no index
-Inclusão da pasta com meu currículo

Juliana Mokrejs

---

index.html
students/claudia_batista/claudia_batista.html

alteração dos nomes dos arquivos e add de conteúdo no arquivo cv Claudia Batista.

file name change

---

index.html
students/barbara_aguilar/barbara_aguilar.html

create my personal curriculo file

barbara aguilar curriculo

---

index.html
students/wanessa_marcondes/wanessa_marcondes.html

alterado nome, id e link no arquivo index
criado arquivo cv wanessa_marcondes

alterado nome, id e link no arquivo index

---

index.html
students/example/vanessa_ribeiro/vanessa_ribeiro.html
students/vanessa_ribeiro/vanessa_ribeiro.html

adicionado o link no index.html e a pasta vanessa_ribeiro com o arquivo vanessa_ribeiro.html

cv - Vanessa Ribeiro

---

index.html
students/nicole_almeida/nicole_almeida.html

Adiciona página do CV Nicole Almeida e altera links de redirecionamento.

CV Nicole Almeida

---

index.html
students/ariane_ueti/ariane_ueti.html

Alterações no Index:
Nome da Aluna
Div Id
Link para página pessoal
Adicionado página de Currículo personalizada

Adicionada página de Currículo de Ariane Ueti

---

students/sara_martins/sara_martins.html

Preenchi experiências, formação acadêmica, cursos, habilidades

Sara martins

---

students/priscila_santtos/priscila_santtos.html

Inclusão das experiências no cv no priscila_santtos.html

inclusão das experiências no cv

---

index.html
students/thaylla_christine/thaylla_christine.html

- Criação da pasta
- Criação arquivo para CV
- Alteração do index.html: 
- Inclusão do nome
- Alteração do caminho do arquivo .html

Thaylla Christine

---

students/gabriela_daltoe_fortuna/cv_gabriela_daltoe_fortuna.html

Edição do html com o currículo completo.

Edição de conteúdo CV Gabriela

---

index.html
students/alessandra_souza/alessandra_souza.html

Editei meu nome, onde trabalhei, onde estudei e meu outros interesses.

Adicionando edições do CV Alessandra Souza

---

students/silvia_dorosz/silvia_dorosz.html

Adicionei a pagina silvia_dorosz, por favor verifique se está tudo correto.

adicionar a pagina silvia_dorosz

---

students/ariane_ueti/ariane_ueti.html

Foi corrigido alguns erros de escrita nos textos;
Alterado as Skills para algo mais próximo do conhecimento adquirido.

Corrigido erros de escrita, alterado skills

---

students/barbara_aguilar/barbara_aguilar.html

add sections about me, works ans study

add sections about me, works ans study

---

students/barbara_aguilar/barbara_aguilar.html

fixed links, add section interested and skills.
Finished

Barbara aguilar

---

index.html
students/alessandra_souza/alessandra_souza.html

Finalizando edições do CV Alessandra Souza

---

students/juliana_mokrejs/juliana_mokrejs.html

inseri um novo item na seção de 'no que já trabalhei'

novo item adicionado

---

students/alessandra_souza/alessandra_souza.html

Corrigindo erros de digitação

---

students/barbara_aguilar/barbara_aguilar.html

add new skills

---

students/fernanda_santo/fernanda_santo.html

cv - Fernanda Santo

---

index.html
students/natalya_peixoto/natalya_peixoto.html

updates skills

---

students/priscila_santtos/priscila_santtos.html

Inclusão do h3 com class na área de experiência profissional.

Add dos cursos, experiências de trabalho, formação e alteração no css

---

students/priscila_santtos/priscila_santtos.html

correção no html

---

students/joseline_correa/joseline_correa.html

Kevin, sei que o prazo expirou mas gostaria de corrigir uns errinhos que identifiquei.
Grande abraço.

Correção ortográfica do conteúdo

---

index.html

Faltava um "s" no caminho do link para o meu currículo

correcao do link Vanessa Ribeiro

---

students/hellen_brunelli/hellen_brunelli.html

Hellen brunelli

---

students/juliana_mokrejs/juliana_mokrejs.html

inclusão do projeto Pet Especial seção "No que já trabalhei"

inclusão do projeto final

---

students/priscila_santtos/priscila_santtos.html

correção de textos no html

---

students/bruna_gil/bruna_gil.html

- Atualização das informações na área de cursos e eventos
- Correção gramatical

Update info at brunagil page
